service: ts-api
# app and org for use with dashboard.serverless.com
app: ts-api
org: tanachstudy101

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
      Resource: "*"

functions:
  contact:
    handler: handler.contact
    events:
      - http:
          path: api/contact
          method: post
    environment:
      FROM_EMAIL: ${param:FROM_EMAIL}
      TO_EMAIL: ${param:TO_EMAIL}
